#!/bin/bash

# This script removes files ending with # or ~ in their names from current
# directory where it is run

vfiles=$(ls -a | sed -En '/[~#]$/p')
vfound=$(ls -a | sed -En '/[~#]$/p' | wc -l)


#if no matching file is found
if [ $vfound -eq 0 ]; then
    echo -e "No files terminating with '~' or '#' in directory\n"
else
    # confirm delete intention
    echo -e "\nFound $vfound file(s) terminating with '~' or '#'"
    read -n1 -p "PROCEED TO DELETE THEM ALL? [y/n]: " vans

    #if response is yes, delete else terminate
    if [ $vans == 'y' -o $vans == 'Y' ]; then
	echo $'\n'"Deleting $vfound file(s) ..."
	sleep .5

	for vfile in $vfiles; do
	    if (("$MAX_TTL")); then
		rmf $vfile
	    else
		rm -f $vfile
	    fi
	done
	echo -e "Done\n"

    elif [ $vans == 'n' -o $vans == 'N' ]; then
	echo -e "\nNoted. Delete aborted ...\n"
    else
	echo -e "\nUnknown response, try again.\n"
    fi
fi
