#!/usr/bin/env bash
# moves files to the ~/.trash directory

dest="/home/$USER/.trash"


# if args not supplied, exit with msg
if (( $# == 0 )); then
	>&2 echo "trash: missing operand"
	exit 1
fi

# else move each file
for file in $@; do
	# if file doesn't exist, print message and exit
	if [ ! -e "$file" ]; then
		>&2 echo "file '$file' doesn't exist"
	else
		# if trash directory doesn't exist, create it
		if [[ ! -e "$dest" || ! -d "$dest" ]]; then
			mkdir $dest
			if (( $? != 0 )); then
				exit 1
			fi
		fi

		# if file already exists in trash, rename it
		tempfile="$dest/$(basename $file)"
		if [ -e "$tempfile" ]; then
			eval "mv $tempfile $tempfile.old"
		fi

		# move file to trash
		eval "mv $file $dest"
	fi
done
